'''Base generator interfaces and variation containers.

This module defines the common configuration, variation, and generator
interfaces used by the bias-variance study generators.
'''

from abc import ABC, abstractmethod
from collections.abc import Iterable
from dataclasses import dataclass

import numpy as np
import pandas as pd


@dataclass(frozen=True, slots=True)
class VariationGeneratorConfig(ABC):
    '''Configures generator settings.

    Generator configuration objects define the variation labels that a
    generator can produce.
    '''

    @property
    @abstractmethod
    def variation_labels(self) -> tuple[str, ...]:
        '''Return all variation labels configured for the generator.

        Returns
        -------
        tuple[str, ...]
            The labels for each variation that can be generated.
        '''
        raise NotImplementedError


@dataclass(frozen=True, slots=True)
class Variation[VaritionGeneratedT]:
    '''Represents a generated variation.

    A variation stores the label for the generated value, the random seed used
    to create it, and the generated value itself.

    Attributes
    ----------
    label : str
        The identifier of the generated variation.
    random_state : int | None
        The random seed used to generate the variation, if provided.
    generated : VaritionGeneratedT
        The value produced by the generator.
    '''
    label: str
    random_state: int | None
    generated: VaritionGeneratedT

    @staticmethod
    def _validate_label(label: str) -> None:
        '''Validate a variation label.

        Parameters
        ----------
        label : str
            The label to validate.

        Raises
        ------
        TypeError
            If ``label`` is not a string.
        ValueError
            If ``label`` is empty or only whitespace.
        '''
        if not isinstance(label, str):
            raise TypeError(
                'label must be a string.'
            )

        if label.strip() == '':
            raise ValueError(
                'label cannot be empty string or whitespace.'
            )

    @staticmethod
    def _validate_random_state(random_state: int | None) -> None:
        '''Validate a random seed.

        Parameters
        ----------
        random_state : int | None
            The random seed to validate.

        Raises
        ------
        TypeError
            If ``random_state`` is not an integer or ``None``.
        ValueError
            If ``random_state`` is outside NumPy's supported seed range.
        '''
        if (
            not isinstance(random_state, int)
            or isinstance(random_state, bool)
        ) and random_state is not None:
            raise TypeError('random_state must be an integer or None.')

        if random_state is not None and not (0 <= random_state < 2**32):
            raise ValueError(
                'random_state out of bounds.'
            )

    def __post_init__(self) -> None:
        '''Validate the variation label and random seed.'''
        self._validate_label(self.label)
        self._validate_random_state(self.random_state)


class VariationGenerator[VaritionGeneratedT](ABC):
    '''Produces labeled variations for one study iteration.

    A generator creates one or more ``Variation`` objects using its configured
    labels and an optional random seed.
    '''

    @property
    @abstractmethod
    def variation_labels(self) -> tuple[str, ...]:
        '''Return all labels generated by this generator.

        Returns
        -------
        tuple[str, ...]
            The labels associated with the generated variations.
        '''
        raise NotImplementedError

    @abstractmethod
    def generate(
        self,
        *,
        random_state: int | None = None,
    ) -> Iterable[Variation[VaritionGeneratedT]]:
        '''Generate one variation per configured label.

        Parameters
        ----------
        random_state : int | None, default = None
            Seed used to make generation reproducible.

        Returns
        -------
        Iterable[Variation[VaritionGeneratedT]]
            The generated labeled variations.
        '''
        raise NotImplementedError

    @staticmethod
    def _validate_dataset(dataset: pd.DataFrame) -> None:
        '''Validate a dataset used by data-based generators.

        Parameters
        ----------
        dataset : pd.DataFrame
            Dataset to validate before generating variations.

        Raises
        ------
        TypeError
            If ``dataset`` is not a pandas DataFrame or contains non-real
            numeric columns.
        ValueError
            If ``dataset`` is empty or contains non-finite values.
        '''
        if not isinstance(dataset, pd.DataFrame):
            raise TypeError("Base dataset must be a pandas DataFrame.")

        if dataset.empty:
            raise ValueError(
                "Base dataset must contain at least one row and column."
            )

        invalid_columns = [
            column
            for column in dataset.columns
            if (
                not pd.api.types.is_numeric_dtype(dataset[column])
                or pd.api.types.is_bool_dtype(dataset[column])
                or pd.api.types.is_complex_dtype(dataset[column])
            )
        ]
        if invalid_columns:
            raise TypeError(
                "Noise can only be applied to real numeric columns. "
                f"Invalid columns: {invalid_columns!r}"
            )

        values = dataset.to_numpy(dtype=float)
        if not np.isfinite(values).all():
            raise ValueError(
                "Base dataset must contain only finite values."
            )